<h2>Merge</h2> 

<form method="post" action="merge"> 

	<fieldset> 

		<legend>Dollar A</legend> 

		<label for="merge-id1">Identifier:</label> 
		<input id="merge-id1" type="text" name="id1" value=""/> 

		<label for="merge-secret1">Secret:</label> 
		<input id="merge-secret1" type="text" name="secret1" value=""/> 

	</fieldset> 

	<fieldset> 

		<legend>Dollar B</legend> 

		<label for="merge-id2">Identifier:</label> 
		<input id="merge-id2" type="text" name="id2" value=""/> 

		<label for="merge-secret2">Secret:</label> 
		<input id="merge-secret2" type="text" name="secret2" value=""/> 

	</fieldset> 

	<button type="submit">Merge</button> 

	<div class="response"></div> 

</form> 
